

# Zebu Language Patterns

zebu = {"I'm wondering if…": "\nI'm wondering if that comfortable feeling in your feet \nwill spread up into the rest of your body.\nI'm wondering if you can pretend that you never smoked in your life and \nimagine what it is like to go through a typical day.\nI didn't tell you to do anything, I was just wondering...",
        "Maybe you'll _____.": "\nMaybe you'll direct some embedded commands to people next time you talk to them.\nMaybe you'll dream of new ways to say things tonight.\nMaybe you'll spot the hidden commands in sentences.",
        "You probably already know…": "\nYou probably already know how useful indirect communication really is.",
        "Don't _____ too quickly.": "\nThis phrase implies that what i suggest will definitely happen,\nand all that matters is *when* it happens.\nAnd if you resist you might internally \nsay, 'Oh yeah, who says I cant do it quickly!? I'll show you!'\nDon't release all the tension in your body too quickly,\njust relax and listen to the sounds around you.",
        "Can you imagine…": "\nPeople are more likely to do what is familiar, \nand imagining things is a great way to create familiarity.\n\nCan you imagine all the situations where you would use \nthis language pattern if you fully learn it?.",
        "One can, <name>, _____": "\nBy adding the person's name, you make the command \nmuch more powerful.\n\nOne can, Eve, feel good for no reason at all.\nOne can, Sara, enjoy the experience of hypnosis without \nknowing exactly what is going to happen.\n\nWho can? ... One can. We're not talking about you, Joe.",
        "You might notice the feelings ... as you…": "\n'You might notice the feelings' directs the attention to \nthe inner body sensations, which is good for hypnotic inductions.\n'As you' provides another opportunity for an indirect suggestion.\n\nYou might notice the feelings in your feet as \nyou relax them completely.",
        "A person might, <name>, _____.": "\nSay the name close to the second half of the sentence, and it \nbecomes a personal embedded command.\n\nA person might, <name>, find a great reason to finally \nmake that change in your life.",
        "One could _____, because…": "\n'Because' is the magic word, because it lends \ncredibility to whatever goes before it.",
        "You can _____ because…": "\nHere's the 'because' again.\nYou can just use it and discover how powerful it is, \nbecause you can pretty much say anything you want after it. \nYou can even use it in everyday conversations, because people love to hear reasons for things.",
        "You can _____, can you not?": "\n'Can you not' is such a great way to end a statement. \nIt turns it into a question which is less threatening, and \nit's so confusing to try and disagree with. \nYou can relax into that chair, can you not?\nYou can allow new solution to come to you, can you not?.",
        "I don't know if _____.": "\nI don't know if you're going to like this game better \nthan any other learning game you've ever played. I don't know which parts in particular you are \ngoing to enjoy the most.\nI really don't know if this experience is going to change \nyour life. Don't ask me, I don't know.",
        "You might notice how good… feels, when you…": "\nThe hidden assumption is that what I'm suggesting feels good, \nand the 'when you' part further assumes that you're going to do it.\n\nYou might notice how good your eyes feel when they close and remain closed.\nYou might notice how good your arms feel when you relax them as they rest on the chair.",
        "Will you …, or …, or …": "\nThis is the form of infinite choice, and I'll cover all the \npossibilities so you can't help but do what i say.\nAnd if you get into the habit of doing what I say, sometime I \nmay begin to actually lead you.\nWill your hand begin to lift up automatically, \nor will it relax just where it is, or will you notice \ncertain sensations in your hand that you can enjoy.",
        "I woudn't tell you to _____, because…": "\nI wouldn't tell you (here I am telling you anyway), and you can't \ndisagree, because I said that I wouldn't tell you.\nAnd I use the magic word 'because' to make another\ncomment, *because* it lends authority to what i just said \nand it carries attention away from the embedded command before \nyou consciously recognize it.",
        "How would it feel if you…?": "\nIn order to answer this question you have to imagine what I propose.\n\nHow would it feel if you felt at peace in that unpleasant situation?",
        "I could tell you that but…": "\nI could tell you that ... , but I won't, so you have no reason to resist \nor take offense at what I just didn't tell you. \nI could tell you that this experience will give you more \nconfidence and self-assurance, but I would rather let you \ndiscover that for yourself.",
        "Sooner or later…": "\nSooner or later you will resolve this present difficulty, and begin to enjoy the simple things in life again.",
        "Sometime…": "\nSometime you're going to feel better about this.\nSometime you are going to understand this from a viewpoint where it all makes sense.\nSometimes you might indirectly get a person to imagine a situation where they have the resources you want them to feel.",
        "Eventually…": "\nEventually everything comes to pass.\n\nEventually you will develop a deep understanding of these difficult \nevents in your life, and you will find some hidden value in them. \nEventually, indirect language patterns will become second nature to you. Imagine that.",
        "Try to resist…": "\n'Try to resist' implies that you will try, but you won't be able to do it.\nYou can use your voice inflection to emphasize the implication.\n\nTry to resist a deepening sense of relaxation as you breathe.\nTry to resist the sensation that your hands are becoming so relaxed that they just won't move.",
        "You might not have noticed…": "\nYou might not have noticed how often you direct peoples awareness\nwhile you are talking to them. Directing awareness to various parts \nof the body generally creates relaxation and cofusion, both induce hypnosis.\n\nYou might have noticed the sounds in the background, the contact \nof your body and your clothes and the way the chair holds your body.",
        "Some people…": "\nSome people get feelings of comfort in this room and want to go into a trance right away.",
        "Can you really enjoy…": "\nCan you really enjoy going deeper and deeper into feelings of comfort?\nCan you really enjoy taking a deep breath and relaxing fully.",
        "What happens when you _____?": "\nWhat happens when you decide that that person or problem doesn't bother you any longer.",
        "You might notice the sensations in… while you…": "\nYou might notice the sensations in your body while it relaxes deeply and \nyou pretend that your body is completely asleep while your mind reminds awake.",
        "One doesn't have to, <name>, _____.": "\nOne doesn't have to, <name>, relax deeper and deeper as you focus on your breathing.",
        "People don't have to, <name>, _____.": "\nPeople don't have to, <name>, listen deeply to the sounds of the environment.",
        "You may not know if _____.": "\nYou may not know if you will enjoy this moment now, and if you do, you'll feel very happy.",
        "It's easy to _____, is it not?": "\n'is it not?' changes a statement to a question, and it is hard to resist it, is it not?\nIt's very esay to forget your troubles, is it not?\nIt's easy to discover something special deep inside, is it not?",
        "A person may not know if _____.": "\nA person may not know if your whole body is relaxing more and more.",
        "You are able to _____.": "\nYou are able to relax you hands completely.\nYou are able to feel a sense of joy and comfort.",
        "<fact>, <fact>, <fact>, and _____.": "\nYou can become aware of the sounds in the background, as you hear the sound of my voice, noticing your breathing and sensations in your body, and you release all the tension.",
        "A person is able to _____.": "\nA person is able to eat less food and enjoy it even more when you savor each mouthful and eat it slowly.",
        "…once told me, _____.": "\nMy babysitter once told me, 'let go of all your troubles, forget everything, get comfortable and go into a deeply relaxed state.",
        "…said, _____.": "\nA wise person once said, 'when you use quotes you can say things indirectly, \nyou can tell someone to let the body relax deeply and breathe naturally.",
        "If you _____, then…": "\nIf you imagine yourself in your favorite place, then you will feel feelings of comfort in your body\nIf you rest your hands on your lap, then you'll be ready to begin.",
        "When you _____, then…": "\nWhen you get in touch with that knowing and loving part of yourself, then an opportunity will open up for \ndeep transformation.",
        "Will you _____, now, or will you _____?": "\nWill you close your eyes now, or will you keep them open while you release tension in other parts of your body first.",
        "You may or may not _____.": "\nYou may or may not notice the comfortable sensation in your hands.",
        "I'm wondering if you'll _____, … or not.": "\nIm wondering if you will effortlessly learn all those things you want to master, ... or not",
        "People can, you know, _____.": "\nI'm talking about what other people can do, I'm not talking about you!\n\nPeople can, you know, find ways to make this changes effortlessly, without even trying.",
        "Maybe you haven't… , yet.": "\nMaybe you haven't realized or maybe you have, \nbut when that 'yet' comes along, it implies that you certainly will.\nMaybe you haven't reached the pinaccle of self-realization, yet.",
        "One might, you know, _____.": "\nOne might, you know, become aware of all the good things in life and feel joyful about them.",
        "You might want to _____, … now.": "\nYou might want to close your eyes, ... now.\nYou might want to let that feeling of comfort move up your arm, ... now.",
        "You could _____.": "\nYou could breathe, relax, and be certain, that you will always find the way thoughout your life.",
        "You might _____.": "\nYou might realize that you can learn infintely valueable lessons from your troubles.",
        "A person could, <name>, _____.": "\nA person could, <name>, find a way to solve your problem while enjoying life and flowing comfortably.",
        "You may _____.": "\nYou may get confused about what used to bother you.",
        "One may, <name>, _____.": "\nOne may, <name>, forgive someone even if you dont think you want to.",
        "A person may _____, because…": "\nA person may become motivated to improve, because it's a natural thing to happen.\n(the 'because' could be somthing illogical, like 'because the sky is blue and the land is vast')",
        "You don't have to _____.": "\nYou don't have to help me with the dishes, really."}


